name: ToggleLogStripping
version: 1.0.0
main: me.arrivals.togglelogstripping.Main
api-version: 1.19
authors: [ arrivals ]
description: End the suffering!
website: https://andremoire.com
commands:
  logstrip:
    description: Commands for ToggleLogStripping.
    usage: /<command>
    aliases: [ lstrip ]